# Generated by Django 5.0.6 on 2025-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_profilemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='', max_length=255, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(default='', help_text='Organization username will be used for museume email address', max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
            preserve_default=False,
        ),
    ]
