# Generated by Django 5.0.6 on 2025-02-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='custom email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(help_text='Organization username will be used for museume email address', max_length=255, unique=True, verbose_name='username'),
        ),
    ]
