# Generated by Django 5.0.6 on 2025-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_plan_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY')], default='USD', max_length=3),
        ),
    ]
