# Generated by Django 5.0.6 on 2025-03-22 00:45

import os

import stripe
from django.db import migrations



def create_plans(apps, schema_editor):
    Plan = apps.get_model('billing', 'Plan')
    plans = Plan.objects.bulk_create([
        Plan(
            name="フリープラン",
            amount="0",
            currency="JPY",
            interval="month",
            features="合計枚数50枚まで"
        ),
        Plan(
            name="プレミアプラン",
            amount="550",
            currency="JPY",
            interval="month",
            features="無制限"
        )
    ])

    # Create stripe prices for each plan
    STRIPE_PRODUCT_ID = os.getenv('STRIPE_PRODUCT_ID')
    for plan in plans:
        if plan.currency == 'USD':
            unit_amount = int(plan.amount * 100),  # Amount in cents
        else:
            unit_amount = int(plan.amount)
        stripe_price = stripe.Price.create(
            product=STRIPE_PRODUCT_ID,
            unit_amount=unit_amount,
            currency=plan.currency,
            recurring={"interval": plan.interval},
            nickname=plan.name,
            metadata={"features": plan.features},
        )
        plan.stripe_price_id = stripe_price.id
        plan.save()


def delete_plans(apps, schema_editor):
    Plan = apps.get_model('billing', 'Plan')
    # Deleting all Plan objects inserted by the migration
    Plan.objects.filter(
        name__in=["フリープラン", "プレミアプラン"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_plan_currency'),
    ]

    operations = [
        migrations.RunPython(create_plans, reverse_code=delete_plans),
    ]
