# Generated by Django 5.0.6 on 2025-02-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0008_alter_artistclass_options_alter_artistclass_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
