# Generated by Django 5.0.6 on 2025-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0009_artistclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
