# Generated by Django 5.0.6 on 2025-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0010_payment_stripe_payment_intent_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistclass',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY')], default='USD', max_length=3),
        ),
    ]
