# Generated by Django 5.0.6 on 2025-02-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0011_artistclass_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistclass',
            name='thumbnail',
            field=models.ImageField(default='https://url.com', upload_to='artist_class_thumbnails/', verbose_name='thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
